name: CI

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      
      - name: Lint
        run: npm ci
        run: npm run lint

      - name: Test
        run: npm run test